using System;
using Newtonsoft.Json;

namespace Essensoft.AspNetCore.Payment.Alipay.Domain
{
    /// <summary>
    /// AlipayOverseasRemitFxtradeorderCreateModel Data Structure.
    /// </summary>
    [Serializable]
    public class AlipayOverseasRemitFxtradeorderCreateModel : AlipayObject
    {
        /// <summary>
        /// the unique id on block chain generated by the caller to represent this remit operation
        /// </summary>
        [JsonProperty("bc_remit_id")]
        public string BcRemitId { get; set; }

        /// <summary>
        /// currency pair
        /// </summary>
        [JsonProperty("currency_pair")]
        public string CurrencyPair { get; set; }

        /// <summary>
        /// extended info
        /// </summary>
        [JsonProperty("extend_info")]
        public string ExtendInfo { get; set; }

        /// <summary>
        /// fx trade orderId
        /// </summary>
        [JsonProperty("fx_trade_order_id")]
        public string FxTradeOrderId { get; set; }

        /// <summary>
        /// fx trade side
        /// </summary>
        [JsonProperty("fx_trade_side")]
        public string FxTradeSide { get; set; }

        /// <summary>
        /// the Mid of the receiver allocated by net.
        /// </summary>
        [JsonProperty("receiver_mid")]
        public string ReceiverMid { get; set; }

        /// <summary>
        /// the Mid of the sender allocated by net.
        /// </summary>
        [JsonProperty("sender_mid")]
        public string SenderMid { get; set; }

        /// <summary>
        /// { "currency":"CNY", "value":"100000" }
        /// </summary>
        [JsonProperty("trans_amount")]
        public Money TransAmount { get; set; }
    }
}
